name: bloc_class
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # To bring business logic in the code called cubit & state Blocs
  flutter_bloc: ^8.1.6
  bloc: ^8.1.1
  # Compares the code snippets during testing mode.
  equatable: ^2.0.7
  # For internet checkup if online or not
  connectivity_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Use to test code snippets
  test: ^1.24.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  # Uncomment and customize these sections if needed:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
